name: goostserver
version: 0.010
main: me.goost.goostserver.GoostServer

depend: [ProtocolLib]

commands:
  job:
    description: Sets your job to
  test:
    description: testing things
  com:
    description: get money for admin
  coitem:
    description: get items for admin
  col:
    description: character level
  staff:
    description: staffcommand
