name: goostserver
version: 1.0
main: me.goost.goostserver.GoostServer
api-version: '1.20'
description: Plugin made by GOOST.
authors: [GOOST]
depend: [ProtocolLib]

commands:
  job:
    description: Sets your job to
  test:
    description: testing things
  com:
    description: get money for admin
  coitem:
    description: get items for admin
  col:
    description: character level
  staff:
    description: staffcommand
  showjob:
    description: showjobs
  coentity:
    description: spawn entity
  worldtp:
    description: tp to world
  sethome:
    description: sethome
  home:
    description: go home
  npc:
    description: spawn npcs